URL_1 = "https://www.chitai-gorod.ru/"

token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3VzZXItcmlnaHQiLCJzdWIiOjIxMDg2NjYwLCJpYXQiOjE3Mjg2Nzc1MzksImV4cCI6MTcyODY4MTEzOSwidHlwZSI6MjB9.foMcn-gEYNUaorAmAgqSIgIoA6iJbquauLW5VscZijc"

